config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/likes',   to: 'artciles#show_liked_article'
    resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :article_likes
  resources :artciles, only: [:create, :show, :destroy] do 
    member do
      resources :article_likes, only: [:create], as: 'article_likes_omar'
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/artcile.rb
class Artcile < ApplicationRecord
  belongs_to :user
  has_many :article_likes
  has_many :likes, through: :article_likes
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :contant, presence: true
  validates :title, presence: true
end

app/controllers/artciles_controller.rb
class ArtcilesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :logged_in_user, only: [:create, :show, :destroy]

  #create new artcile
  def create
    @artciles = current_user.artciles.build(artcile_params)
    if @artciles.save
      flash[:success] = "Artcile created!"
      redirect_to root_url
    else
      render 'welcome/index'
    end
  end
  
  #show all fav artciles
  def show_liked_article
    @articles = current_user.likes
    render 'artciles/likes'
  end

private

    #get artcile paramiters
    def artcile_params
      params.require(:artcile).permit(:title, :contant)
    end
    
    #find artcile by id
    def set_article
      @artciles = Artcile.find(params[:id])
    end
end

app/helpers/artciles_helper.rb
module ArtcilesHelper
end

app/views/artciles/_artcile.html.erb
<li id="artcile-<%= artcile.id %>">
  <span class="user lead"><%= link_to artcile.user.name, artcile.user %></span>
  <span class="content lead"><%= link_to artcile.title, artcile_path(artcile.id) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(artcile.created_at) %> ago.
  </span>
</li>

app/views/artciles/_article_form.html.erb
<div id="follow_form">
<% if current_user.liked?(@artciles) %>
  <%= render partial: "unlike", locals: {article: @artciles} %>
<% else %>
  <%= render 'like' %>
<% end %>
</div>

app/views/artciles/_like.html.erb
<%= form_for current_user.likes.build , as: :post, url: article_likes_omar_index_path(@artciles) do |f| %>
  <%= f.submit "like", class: "btn btn-primary" %>
<% end %>

app/views/artciles/_unlike.html.erb
<%= form_for(current_user.article_likes.find_by(article_id: @artciles.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unlike", class: "btn" %>
<% end %>

app/views/artciles/likes.html.erb
<% if @articles.any? %>
  <ol class="microposts">
    <%= render @articles %>
  </ol>
<% end %>

app/views/artciles/show.html.erb
<%provide(:title, @artciles.title)%>
<section class="user_info">
  <h1>
    <%= @artciles.title %>
  </h1>
  <p class="lead">
    <%= @artciles.contant %>
  </p>
  <div>
    <div> <%= render 'article_form' if logged_in? %> </div>
  </div>
</section>