config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/likes',   to: 'artciles#show_liked_article'
    resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :article_likes
  resources :artciles, only: [:create, :show, :destroy] do 
    member do
      resources :article_likes, only: [:create], as: 'article_likes_omar'
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

   <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Articles app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Fav Artciles", likes_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>